// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0KviTXTLsWycDS8jsGjaVzfh8rEgEb0Y',
    appId: '1:651397027693:web:c724ee4598ef1d74212c64',
    messagingSenderId: '651397027693',
    projectId: 'pogo-teams-host',
    authDomain: 'pogo-teams-host.firebaseapp.com',
    storageBucket: 'pogo-teams-host.appspot.com',
    measurementId: 'G-XYHVBMDYL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY2H7NwYqg_0WzhJUHqpFm9fuf9F0-Ayw',
    appId: '1:651397027693:android:e676cd1007623e47212c64',
    messagingSenderId: '651397027693',
    projectId: 'pogo-teams-host',
    storageBucket: 'pogo-teams-host.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn9mOa7MEa3veMqaVnYavrJiN0S9xNS1Y',
    appId: '1:651397027693:ios:5deeb50f16e77c0f212c64',
    messagingSenderId: '651397027693',
    projectId: 'pogo-teams-host',
    storageBucket: 'pogo-teams-host.appspot.com',
    iosClientId: '651397027693-p6sa3t0aea3bpk33ue35kj7vj65un7af.apps.googleusercontent.com',
    iosBundleId: 'com.pogoTeams',
  );
}
